export const data = [
    {
      id: 1,
      startDate: "21-02-2024",
      endDate: "22-02-2024",
      startTime: "05:30:00",
      endTime: "07:30:00",
      location: "Cheruparambil Devasthanam, Kerala, India",
      title: "Cheruparambil Devasthanam Puja",
      img: "/assets/maninagam.jpg",
      desc: "You%20All%20Are%20Welcome%20To%20Cheruparambil%20Devasthanam%20Puja",
      contactPerson: "Aneesh Sasidharan",
      contactPersonEmail: "aneesh.exactus@gmail.com",
      images: [
        "http://res.cloudinary.com/dta3mcayk/image/upload/v1708578908/test/y1tjhlkt1ahfsugmetjj.png",
        "http://res.cloudinary.com/dta3mcayk/image/upload/v1708578910/test/xj3rjoiocfbpxfabzxoe.png",
        "http://res.cloudinary.com/dta3mcayk/image/upload/v1708578912/test/l7sduzxvnlm0knhzdgwb.png",
        "http://res.cloudinary.com/dta3mcayk/image/upload/v1708578915/test/t2vscersn3mibfzs9ttm.png",
        "http://res.cloudinary.com/dta3mcayk/image/upload/v1708578918/test/bayckqv0at23oaz9lc7t.png",
      ],
    },
    {
      id: 2,
      startDate: "21-02-2024",
      endDate: "22-02-2024",
      startTime: "05:30:00",
      endTime: "07:30:00",
      location: "Cheruparambil Devasthanam, Kerala, India",
      title: "Cheruparambil Devasthanam Puja",
      img: "/assets/maninagam.jpg",
      desc: "You%20All%20Are%20Welcome%20To%20Cheruparambil%20Devasthanam%20Puja",
      contactPerson: "Aneesh Sasidharan",
      contactPersonEmail: "aneesh.exactus@gmail.com",
      images:[]
    },
    {
      id: 3,
      startDate: "21-02-2024",
      endDate: "22-02-2024",
      startTime: "05:30:00",
      endTime: "07:30:00",
      location: "Cheruparambil Devasthanam, Kerala, India",
      title: "Cheruparambil Devasthanam Puja",
      img: "/assets/maninagam.jpg",
      desc: "You%20All%20Are%20Welcome%20To%20Cheruparambil%20Devasthanam%20Puja",
      contactPerson: "Aneesh Sasidharan",
      contactPersonEmail: "aneesh.exactus@gmail.com",
      images:[]
    },
    {
      id: 4,
      startDate: "21-02-2024",
      endDate: "22-02-2024",
      startTime: "05:30:00",
      endTime: "07:30:00",
      location: "Cheruparambil Devasthanam, Kerala, India",
      title: "Cheruparambil Devasthanam Puja",
      img: "/assets/maninagam.jpg",
      desc: "You%20All%20Are%20Welcome%20To%20Cheruparambil%20Devasthanam%20Puja",
      contactPerson: "Aneesh Sasidharan",
      contactPersonEmail: "aneesh.exactus@gmail.com",
    },
  ];
